package Ventanas;

import Ventanas.DatosUniforme;
import Ventanas.DatosNormal;
import Ventanas.DatosExponencial;
import distribuciones.*;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import testChiCuadrado.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aleex
 */
public class Principal extends javax.swing.JFrame {

    private Distribucion distribucion;
    private Datos datos;
    private ArrayList numeros;
    private TestChiCuadrado testChi;
    private int intervalos;

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDistribucion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNum = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();
        btnGrafico = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnChiCuadrado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIntervalos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Generador de variables aleatorias");

        jLabel2.setText("Selecciones una Distribucion: ");

        cmbDistribucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion...", "Distribución Normal", "Distribución Exponencial", "Distribución Uniforme", "Distribución Poisson", " " }));
        cmbDistribucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDistribucionActionPerformed(evt);
            }
        });

        tblNum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Numero Aleatoreo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNum);

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/media_playback_start.png"))); // NOI18N
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grafico-de-barras.png"))); // NOI18N
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad de números a generar: ");

        txtCantidad.setText("0");

        btnChiCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/if_icon-62-document-table_314426.png"))); // NOI18N
        btnChiCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiCuadradoActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de Intervalos:");

        txtIntervalos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGrafico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChiCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGenerar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnChiCuadrado)
                        .addGap(28, 28, 28)
                        .addComponent(btnGrafico)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void agregarFila(double numero)
    {
        DefaultTableModel modelo = (DefaultTableModel) this.tblNum.getModel();
        int numFila = modelo.getRowCount() + 1;
        String[] datos = {String.valueOf(numFila), String.valueOf(numero)}; // Cantidad de columnas de la tabla
        modelo.addRow(datos);
    }
    
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        //genera un ArrayList con todos los números generados
        
        int cantidad = Integer.valueOf(this.txtCantidad.getText());
        this.intervalos = Integer.valueOf(this.txtIntervalos.getText());
        
        if ( cantidad <= 0 || intervalos <= 0 || this.cmbDistribucion.getSelectedIndex() == 0) {
            //en caso de ser cero la cantidad solicitada o negativa no hace nada
            JOptionPane.showMessageDialog(null, "Error: Debe ingresar todos los datos");
            return;
        }
        
        this.numeros = this.distribucion.generarNumeros(cantidad);
        for (Object i: this.numeros)
        {
            this.agregarFila((double)i);
        }
        this.EjecutarTestChi();
    }//GEN-LAST:event_btnGenerarActionPerformed
    
    private void EjecutarTestChi()
        {
            if(this.distribucion instanceof Exponencial)
            {
                this.testChi = new ChiExponencial(this.intervalos, this.numeros,((Exponencial)this.distribucion).getMedia());
            }
            if(this.distribucion instanceof Normal)
            {
                Normal t1 = (Normal)this.distribucion;
                this.testChi = new ChiNormal(this.intervalos, this.numeros,t1.getMedia(), t1.getDesviacionEstandar());
            }
            if(this.distribucion instanceof Poisson)
            {
                Poisson p = (Poisson) this.distribucion;
                this.testChi = new ChiPoisson(this.intervalos, this.numeros,p.getMedia());
            }
            if(this.distribucion instanceof Uniforme)
            {
                this.testChi = new ChiUniforme(this.intervalos, this.numeros);
            }
            this.testChi.ejecutarTest();
        }
    
    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        // TODO add your handling code here:
        /*DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        
        for (int i = 0; i < this.tblNum.getRowCount(); i++)
        {
            dtsc.addValue(Integer.parseInt((this.tblNum.getValueAt(i, 1).toString())), "Observada", this.tablaChi.getValueAt(i, 0).toString());
            dtsc.addValue(Double.parseDouble((this.tablaChi.getValueAt(i, 2).toString())), "Esperada", this.tablaChi.getValueAt(i, 0).toString());
        }
        
        JFreeChart jf = ChartFactory.createBarChart3D("Grafica de frecuencias", "Intervalos", "Frecuencia", dtsc, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel c = new ChartPanel(jf);
        JDialog vtn = new JDialog(new javax.swing.JFrame(), true);
        vtn.add(c);
        vtn.setSize(900, 700);
        vtn.setLocationRelativeTo(null);
        vtn.setVisible(tru*/
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void cmbDistribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDistribucionActionPerformed
        //obtiene la distribución para generar los números aleatorios, derivando a otra ventana para
        // la toma de los datos según qué distribución se solicite
        
        int opc = cmbDistribucion.getSelectedIndex();
        
        switch (opc) {
            case 0:
                break;
            case 1:
                this.datos = new DatosNormal(new JFrame(), true);
                break;
            case 2:
                this.datos = new DatosExponencial(new JFrame(), true);
                break;
            case 3:
                this.datos = new DatosUniforme(new JFrame(), true);
                break;
            case 4:
                this.datos = new DatosPoisson(new JFrame(), true);
                break;
        }
        
        if(opc != 0) {
            datos.setVisible(true);
            this.distribucion = datos.getDistribucion();
        }
                
    }//GEN-LAST:event_cmbDistribucionActionPerformed

    private void btnChiCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiCuadradoActionPerformed
        // TODO add your handling code here:
        TablaChi tchi = new TablaChi(new JFrame(), true);
        tchi.setTestChi(this.testChi);
        tchi.setVisible(true);
    }//GEN-LAST:event_btnChiCuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiCuadrado;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JComboBox<String> cmbDistribucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNum;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIntervalos;
    // End of variables declaration//GEN-END:variables
}
