/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import distribuciones.Distribucion;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import testChiCuadrado.*;

/**
 *
 * @author nicolastomassi
 */
public class TablaChi extends javax.swing.JDialog {
    private TestChiCuadrado testChi;
    
    /**
     * Creates new form TablaChi
     */
    public TablaChi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setTestChi(TestChiCuadrado testChi) {
        this.testChi = testChi;
    }
    
    private void generarTabla(){
        ArrayList<Double> esperadas = this.testChi.getEsperadasAgrupadas();
        ArrayList<Double> observadas = this.testChi.getObservadasAgrupadas();
        ArrayList<double[]> intervalos = this.testChi.getIntervalosAgrupados(); 
        ArrayList<Double> chis = this.testChi.diferenciaYalCuadrado();
        String intervalo;
        
        double observada, esperada, chi;
        
        
        for(int i = 0; i < intervalos.size(); i++)
        {
            observada = Math.round(observadas.get(i)*1000.0) / 1000.0;
            esperada = Math.round(esperadas.get(i)*1000.0) / 1000.0;
            chi = Math.round(chis.get(i)*1000.0) / 1000.0;
            
            intervalo = String.valueOf(intervalos.get(i)[0]) +  " - " + String.valueOf(intervalos.get(i)[1]);
            this.agregarFilas(intervalo, String.valueOf(observada), String.valueOf(esperada), String.valueOf(chi));
        }
    }
    
    private void agregarFilas(String intervalo, String observado, String esperado, String chi)
    {
        DefaultTableModel model =  (DefaultTableModel) this.tablaChi.getModel();
        String datos[] = {intervalo, observado, esperado, chi};
        model.addRow(datos);
        
    }
    
    public void ejecutarTest(){
        this.generarTabla();
        
        
        
        
        if (this.testChi.esAprobado()) {
            this.lblAceptado.setVisible(true);
            this.lblCancelado.setVisible(false);
            
        }
        
        else {
            this.lblCancelado.setVisible(true);
            this.lblAceptado.setVisible(false);
        }
        
        double sumatoria = (Math.round(this.testChi.generarSumatoriaChi() * 1000.0) / 1000.0);
        this.lblChiCalculado.setText(this.lblChiCalculado.getText() + " " + String.valueOf(sumatoria));
        this.lblGrado.setText(this.lblGrado.getText() + " " + String.valueOf(this.testChi.getGradosDeLibertad()));
        this.lblChiTabulado.setText(this.lblChiTabulado.getText() + " " + String.valueOf(this.testChi.getNumeroTabla(this.testChi.getGradosDeLibertad()))); 
    
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChiCalculado = new javax.swing.JLabel();
        lblCancelado = new javax.swing.JLabel();
        lblAceptado = new javax.swing.JLabel();
        lblChiTabulado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaChi = new javax.swing.JTable();
        lblGrado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGraficar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblChiCalculado.setText("X^2 :");
        lblChiCalculado.setToolTipText("");

        lblCancelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/error.png"))); // NOI18N

        lblAceptado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapas-y-banderas.png"))); // NOI18N

        lblChiTabulado.setText("X^2(tabulado) :");
        lblChiTabulado.setToolTipText("");

        tablaChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Intervalo", "fo", "fe", "((fo - fe)^2)/fe"
            }
        ));
        tablaChi.setName(""); // NOI18N
        jScrollPane1.setViewportView(tablaChi);

        lblGrado.setText("Grado de Libertad:  ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Test  Chi-Cuadrado");

        btnGraficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grafico-de-barras.png"))); // NOI18N
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(lblAceptado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(lblCancelado)
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnGraficar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblChiTabulado)
                                    .addComponent(lblGrado)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(lblChiCalculado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGraficar)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCancelado)
                            .addComponent(lblAceptado)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChiTabulado)
                        .addGap(18, 18, 18)
                        .addComponent(lblGrado)
                        .addGap(18, 18, 18)
                        .addComponent(lblChiCalculado)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        //int []observadas = this.testChi.getContadorFrecuencia();
        ArrayList<Double> observadas = this.testChi.getObservadasAgrupadas();
        ArrayList esperadas = this.testChi.getEsperadasAgrupadas();
        ArrayList intervalos = this.testChi.getIntervalosAgrupados();
        for (int i = 0; i < esperadas.size() ; i++)
        {
            double[] intervalo = (double[]) intervalos.get(i);
            //String aux = Math.round(intervalo[0]*100.0) + " - " + Math.round(intervalo[1]*100.0); 
            String aux = intervalo[0] + " - " + intervalo[1];
            System.out.println(aux);
            //Integer aux1 = observadas[i];
            Double aux1 = observadas.get(i);
            dtsc.addValue(Double.parseDouble(aux1.toString()), "Observada", aux);
            dtsc.addValue(Double.parseDouble(esperadas.get(i).toString()), "Esperada", aux);
        }
        
        JFreeChart jf = ChartFactory.createBarChart3D("Grafica de frecuencias", "Intervalos", "Frecuencia", dtsc, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel c = new ChartPanel(jf);
        JDialog vtn = new JDialog(new javax.swing.JFrame(), true);
        vtn.add(c);
        vtn.setSize(1200, 700);
        vtn.setLocationRelativeTo(null);
        vtn.setVisible(true);
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TablaChi dialog = new TablaChi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAceptado;
    private javax.swing.JLabel lblCancelado;
    private javax.swing.JLabel lblChiCalculado;
    private javax.swing.JLabel lblChiTabulado;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JTable tablaChi;
    // End of variables declaration//GEN-END:variables
}
